### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by DDuran19** [DDuran19/tree-planting#2]
Figma: https://www.figma.com/file/yWh266WlTsI6UtiIbWi8IG/Tree-Planting-Petition?node-id=2%3A118&mode=dev

<details>
<summary>Navbar.tsx</summary>

```tsx

import React from "react";
import { Branding } from "./Branding";
import { Navlinks } from "./Navlinks";
import "./style.css";

export const Navbar = () => {
    return (
        <div className="navbar">
            <Branding className="design-component-instance-node" group="image.png" />
            <Navlinks className="design-component-instance-node" />
        </div>
    );
};

```

</details>

<details>
<summary>Branding.tsx</summary>

```tsx
import PropTypes from "prop-types";
import React from "react";
import "./style.css";

export const Branding = ({ group = "group.png" }) => {
    return (
        <div className="branding">
            <img className="group" alt="Group" src={group} />
            <div className="text-wrapper">Tree</div>
        </div>
    );
};

Branding.propTypes = {
    group: PropTypes.string,
};

```

</details>

<details>
<summary>Navlinks.tsx</summary>

```tsx
import React from "react";
import { NavLink } from "./NavLink";
import "./style.css";

export const Navlinks = () => {
    return (
        <div className="navlinks">
            <NavLink color="normal" text="home" />
            <NavLink color="normal" text="about" />
            <NavLink color="normal" text="login" />
            <NavLink color="normal" text="join" />
        </div>
    );
};

```

</details>

<details>
<summary>Navlink.tsx</summary>

```tsx
import PropTypes from "prop-types";
import React from "react";
import { useReducer } from "react";
import "./style.css";

export const NavLink = ({ text, color }) => {
    const [state, dispatch] = useReducer(reducer, {
        text: text || "home",
        color: color || "normal",
    });

    return (
        <div
            className={`nav-link ${state.text} ${state.color}`}
            onMouseLeave={() => {
                dispatch("mouse_leave");
            }}
            onMouseEnter={() => {
                dispatch("mouse_enter");
            }}
        >
            <div className="div">
                {state.text === "home" && <>Home</>}

                {state.text === "about" && <>About</>}

                {state.text === "login" && <>Login</>}

                {state.text === "join" && <>JOIN Petition</>}
            </div>
        </div>
    );
};

function reducer(state, action) {
    switch (action) {
        case "mouse_enter":
            return {
                ...state,
                color: "hover",
            };

        case "mouse_leave":
            return {
                ...state,
                color: "normal",
            };
    }

    return state;
}

NavLink.propTypes = {
    text: PropTypes.oneOf(["home", "about", "join", "login"]),
    color: PropTypes.oneOf(["hover", "normal"]),
};

```

</details>

<details>
<summary>Style</summary>

```css
.navbar {
    align-items: center;
    background-color: var(--variable-collection-color-dark);
    display: flex;
    justify-content: space-between;
    padding: 10px 141px;
    position: relative;
    width: 1440px;
}

.navbar .design-component-instance-node {
    flex: 0 0 auto !important;
}
.branding {
    align-items: center;
    background-color: var(--variable-collection-text-black);
    border: 1px solid;
    border-color: var(--variable-collection-text-white);
    border-radius: 15px;
    display: inline-flex;
    gap: 4px;
    justify-content: center;
    overflow: hidden;
    padding: 3px 21px;
    position: relative;
}

.branding .group {
    height: 36px;
    position: relative;
    width: 25px;
}

.branding .text-wrapper {
    color: var(--variable-collection-text-white);
    font-family: "Inter-Bold", Helvetica;
    font-size: 36px;
    font-weight: 700;
    letter-spacing: 0;
    line-height: normal;
    margin-top: -1px;
    position: relative;
    width: fit-content;
}

.navlinks {
    align-items: center;
    display: inline-flex;
    gap: 36px;
    justify-content: center;
    padding: 6px 21px;
    position: relative;
}

```

</details>

<details>
<summary>Style Guide</summary>

```css
:root {
    --variable-collection-color-accent: rgba(209, 151, 147, 1);
    --variable-collection-color-dark: rgba(84, 91, 85, 1);
    --variable-collection-color-light: rgba(238, 213, 231, 1);
    --variable-collection-color-primary: rgba(204, 199, 174, 1);
    --variable-collection-color-secondary: rgba(246, 206, 200, 1);
    --variable-collection-text-black: rgba(11, 27, 45, 1);
    --variable-collection-text-white: rgba(250, 250, 250, 1);
}

```

</details>
