### ISSUE TITLE
Create Hero section

### ISSUE THREAD

**Issue by DDuran19** [DDuran19/tree-planting#5]
![image](https://github.com/DDuran19/tree-planting/assets/128191960/8ce3c8fd-20e1-456c-89cf-93b0cfa50199)
Figma: https://www.figma.com/file/yWh266WlTsI6UtiIbWi8IG/Tree-Planting-Petition?node-id=2%3A118&mode=dev

<details>
<summary>React</summary>

```tsx

import React from "react";
import "./style.css";

export const Hero = () => {
    return (
        <div className="hero">
            <p className="let-us-save-the">
                <span className="text-wrapper">Let us </span>
                <span className="span">save</span>
                <span className="text-wrapper-2">&nbsp;</span>
                <span className="text-wrapper">the Earth</span>
            </p>
            <p className="div">One tree at a time</p>
            <img className="tree-landscape" alt="Tree landscape" src="tree-landscape-1.png" />
        </div>
    );
};


```

</details>

<details>
<summary>Style</summary>
```css
.hero {
    align-items: center;
    display: inline-flex;
    flex-direction: column;
    justify-content: center;
    padding: 58px 0px;
    position: relative;
}

.hero .let-us-save-the {
    color: var(--variable-collection-text-black);
    font-family: "Inter-Bold", Helvetica;
    font-size: 128px;
    font-weight: 700;
    letter-spacing: 0;
    line-height: normal;
    margin-top: -1px;
    position: relative;
    width: fit-content;
}

.hero .text-wrapper {
    color: #545b55;
}

.hero .span {
    color: #fafafa;
}

.hero .text-wrapper-2 {
    color: #0b1b2d;
}

.hero .div {
    color: var(--variable-collection-color-dark);
    font-family: "Inter-Bold", Helvetica;
    font-size: 36px;
    font-weight: 700;
    letter-spacing: 0;
    line-height: normal;
    position: relative;
    width: fit-content;
}

.hero .tree-landscape {
    height: 695px;
    object-fit: cover;
    position: relative;
    width: 1440px;
}

```

</details>
