### ISSUE TITLE
Create About Section

### ISSUE THREAD

**Issue by DDuran19** [DDuran19/tree-planting#7]
![image](https://github.com/DDuran19/tree-planting/assets/128191960/ede94916-0f90-432b-98fb-9c6f5bb3a3a3)
https://www.figma.com/file/yWh266WlTsI6UtiIbWi8IG/Tree-Planting-Petition?node-id=2%3A118&mode=dev

<details>
<summary>React</summary>

```tsx
import React from "react";
import { AboutHeader } from "./AboutHeader";
import { Description } from "./Description";
import "./style.css";

export const About = () => {
    return (
        <div className="about">
            <div className="frame">
                <AboutHeader type="mission" />
                <Description type="mission" />
            </div>
            <div className="frame-2">
                <AboutHeader type="vision" />
                <Description type="vision" />
            </div>
        </div>
    );
};

```

</details>

<details>
<summary>Style</summary>

```css
.about {
    align-items: center;
    background-color: #ffffff38;
    display: flex;
    flex-direction: column;
    gap: 90px;
    padding: 70px 31px;
    position: relative;
    width: 1440px;
}

.about .frame {
    align-items: flex-start;
    display: inline-flex;
    flex-direction: column;
    gap: 25px;
    height: 295px;
    justify-content: center;
    position: relative;
}

.about .frame-2 {
    align-items: flex-start;
    display: inline-flex;
    flex-direction: column;
    gap: 25px;
    height: 381px;
    position: relative;
}

```
